### ISSUE TITLE
[BUG]: Scheduled backups don't run

### ISSUE THREAD

**Issue by JDiaz11** [jneilliii/OctoPrint-BackupScheduler#12]
**Describe the bug**

Scheduled backups don't run

**Expected behavior**

Automated backups

**Debug Log**

Not seeing debug option in settings

**Screenshots**

<img width="621" alt="Screen Shot 2020-10-27 at 4 00 19 PM" src="https://user-images.githubusercontent.com/9299272/97355781-c75a0700-186d-11eb-881c-bdd57d333859.png">
<img width="727" alt="Screen Shot 2020-10-27 at 4 00 40 PM" src="https://user-images.githubusercontent.com/9299272/97355786-ca54f780-186d-11eb-84f8-2d3cb729ea5c.png">

**Firmware and Version**

Marlin 2.0, OctoPrint 1.4.2, Python 3.7.3, OctoPi 0.17.0, Plugin 0.0.3

**Comment by jneilliii** [comment]
The time is based on your pi's system time. Have you adjusted that in raspi-config for your time zone?
