### ISSUE TITLE
[FR]: S3 Integration - Upload backup into a bucket 

### ISSUE THREAD

**Issue by SnickCH** [jneilliii/OctoPrint-BackupScheduler#13]
**Is your feature request related to a problem? Please describe.**
I like an easy way that is not bound to any specific provider (like google for Gdrive). S3 is a defacto-Standard and is supported from many vendors, providers and even on cheap NAS. I'm aware that S3 has many hundreds of specific API request. For a simple upload of a file to a bucket requires only a put request that all S3-like storage will support. 

**Describe the solution you'd like**
1) Main request: I would like to have the possibility to add an S3-compatible endpoint and that the backup will be written to this bucket. 
2) Additionally the possibility to keep a copy of the backup offline (example: only the last 3 ones offline, so it doesn't fill my disk)

**Describe alternatives you've considered**
I'm aware that the Gdrive plugin does the same (copy to cloud) but only to a specific provider (google). Of course it would be possible to write a plugin for each provider. But in my opinion it is easier just to add a specific protocol like S3.

**Additional context**
If you like to implement this and would need a test account + bucket, feel free to contact me, I can provide you one. For Linux there are already existing tools like s3cmd that could be used for an underlining layer if that would help.

In general: Thank you very much for all your great OctoPrint plugins 👍

**Comment by cp2004** [comment]
Probably makes more sense this was a separate plugin, since there is a 'backup created' event that could be hooked. That means you don't have to install a 'Backup Scheduler' to get cloud/whatever upload features.

**Comment by SnickCH** [comment]
It could be that it makes more sense to have a separated plugin (lige G-Drive upload). It was just an idea and because I would mainly use it with this plugin, I opened a feature request. If it makes more sense to do a new plugin you can close this FR.

**Comment by jneilliii** [comment]
Yeah, that's the reason I wrote the Goggle Drive Backup plugin separately. I would recommend posting on the community forum in the plugins or development topics to see if anyone is interested in developing that. It would be too hard to fork my Google Drive one for the initial structure and just change the file upload commands to work with an S3 API.
