### ISSUE TITLE
[FR]: Non - Pi automatic storage

### ISSUE THREAD

**Issue by KenLucke** [jneilliii/OctoPrint-BackupScheduler#14]
**Is your feature request related to a problem? Please describe.**
I get tired of having to manually download backups, time lapses, etc., etc., to my local disk (the one running the web interface), and deleting them from the Pi to make sure I don't cause the disk to fill (yeah, I use huge disks,  but full disks are my paranoid pet peeve).  Especially as I apparently have an issue that about 70% of the time, when I click a download [no matter whether  it's a main OP feature, or a plugin's], it downloads, but forces a reload of the interface (never been  able to specifically determine why or when it  happens, so 've never filed a bug report)

**Describe the solution you'd like**
The ability to set a destination, either on the local disk, my NAS server on the  local network, or Dropbox [where they'd be automatically mirrored to my local HD for the backups (and anything else, for that matter) to which they would  be automatically saved.

**Describe alternatives you've considered**
Living with it the way it  is.

**Additional context**
It would be absolutely AWESOME if some hook could be put in that any plugin or tab that has a "download" option could be set up to access the location, too.

**Comment by jneilliii** [comment]
So a new plugin just released for webdav backups, the dropbox timelapse plugin (can be configured for being triggered with backups), and my Google Drive Backup plugin do this for you.

**Comment by KenLucke** [comment]
Unfortunately, I don't use WebDAV, nothing Google touches my computer if it can be avoided (i have allll their domains blocked at the router and have to manually allow anything absolutely necessary on a case-by-case basis), and I'm not doing timelapses right now  :)


I wanted a local solution, if  possible.

**Comment by KenLucke** [comment]
What I would envision, if I could write it from scratch, would be a plugin with check boxes for everything  that is downloadable (logs, timelapses, backups, etc) to select what would be copied (and a "delete after copying" checkbox for each) with a configurable path on the local network (for me, that could either  be my Mac or the NAS) or to Dropbox (or Google Drive, for those that use it,  ditto iiCloud storage or other "Cloud storage" locations, even though *I* don't use those if I can help it. It would require that the security credentials for that location be stored, but they could be encrypted using a plugin specific API.

The  plugin would watch for new files to show up in their standard locations, and if they met the criteria, be copied to that location (and optionally deleted)

**Comment by jneilliii** [comment]
I think that new one works with other stuff too, like nas. The idea is out of scope for this one IMO.

**Comment by KenLucke** [comment]
> I think that new one works with other stuff too, like nas. The idea is out of scope for this one IMO.

I didn't see  that anywhere, but I'll look  again.

**Comment by jneilliii** [comment]
Yeah, it was OwnCloud and NextCloud based on the description.

**Comment by jneilliii** [comment]
@KenLucke this might be helpful to you...

https://github.com/jneilliii/OctoPrint-BackupScheduler/wiki/Copy-to-NAS

**Comment by KenLucke** [comment]
I already do this two ways - one, my hourly backups via Time Machine use my NAS as one of the 4 targets for the backup (yes, I live by my recommendations I make to others to backup, backup the backup, and backup the backup backup), and two, I have a background app that once a day backs up all my photography files/lightroom/photoshop stuff to a separate folder on the NAS.  

I was hoping for direct access from the scheduler, but I'll live :)
