### ISSUE TITLE
[FR]: Ability to select were to store de backup.  (f.ex. NAS) 

### ISSUE THREAD

**Issue by nicovankampen** [jneilliii/OctoPrint-BackupScheduler#15]
Hi,
looks like a very usefull plugin. Just started using it.

I'd like to store the backup files on my NAS. As far as i can see there is no possibility for that now. Maybe an idea to put in your next update?

thanks,
Nico

**Comment by jneilliii** [comment]
This is out of scope for this plugin, but there are other plugins that can send completed backups to other storage locations. Right now there are 3 plugins that I'm aware of that will do this, the Dropbox Timelapse plugin (you can register with the backup event), my Google Drive Backup plugin, and there was recently a WebDav Backup plugin added.

**Comment by jneilliii** [comment]
This might help your situation.

https://github.com/jneilliii/OctoPrint-BackupScheduler/wiki/Copy-to-NAS

**Comment by nicovankampen** [comment]
> 
> 
> This might help your situation.
> 
> https://github.com/jneilliii/OctoPrint-BackupScheduler/wiki/Copy-to-NAS

Thanks. that looks like a good solution. I will give it a try.
