### ISSUE TITLE
[BUG]: Scheduled backups do not start

### ISSUE THREAD

**Issue by Masanetz** [jneilliii/OctoPrint-BackupScheduler#16]
**Describe the bug**
Planned backups do not start

**Expected behavior**
Backups run

**Firmware and Version**
OctoPi 0.17, Octoprint 1.5.3, Python 3.7.3, BackupScheduler 0.0.4

I have two instances of Octoprint running on the same Pi4. First backup scheduler worked on the first instance (Port 5000), but not on the second on Port 5100.

Tried some different things, on thing was disabling the original discovery plugin, as I do not need it. Did not help.
After trying some more, I moved both instances to non default ports (5001 and 5002). Now the backup scheduler does not start anymore on both instances...

**Logs**
Checked octoprint.log on both instances, but no trace of backup scheduler in the non working case...

**Comment by jneilliii** [comment]
This is probably related to how the plugin is submitting the backup request to OctoPrint. In this line [here](https://github.com/jneilliii/OctoPrint-BackupScheduler/blob/f75d0356676c97ee421cfadd57541036be12c656/octoprint_backupscheduler/__init__.py#L152) is where I'm having to do an API call to core OctoPrint to perform the backup, and I bet it's not getting the correct port from your config.yaml file potentially. Which instructions did you follow for creating your multiple instances. If you have them configured for different base directories, which I believe is recommended then you just need to configure the server port in config.yaml. 

https://docs.octoprint.org/en/master/configuration/config_yaml.html#server

**Comment by jneilliii** [comment]
I believe I have this fixed with the above commit. I'm going to setup a Release Candidate to allow you to test and verify for me. You can change the Release Channgel in OctoPrint's Software Update settings to Release Candidate and you should get an update notification.

**Comment by Masanetz** [comment]
Didn't even know about setting the port within config.yaml. Changed only the port in "/etc/default/octoprint" and "/etc/default/octoprint2". So only changed commandline parameters. Worked for everything else.
Setting port in config.yaml -> Backup scheduler works (ver. 0.0.4 and 0.0.5rc1).
Removed port from config.yaml, version 0.0.5rc1 worked, but only one time after restaring octoprint and it doesn't delete old backup...

So I'm going the way of setting the port in config.yaml...

Thanks for your quick help.

**Comment by jneilliii** [comment]
I'll look into that issue, because doing it the way that I did in 0.0.5rc1 will prevent future issues because I'm pretty sure that the way that you ran your multiple instances changing the command line to include `--port 5001` is the most common way that all the instructions I've seen for multiple instances tell you to do. Will also look into why deleting might not be working. Might be a similar issue that I just need to hunt down.
