### ISSUE TITLE
[Feature Request] Split Schedules to Have Their Own Options

### ISSUE THREAD

**Issue by CmdrCody51** [jneilliii/OctoPrint-BackupScheduler#2]
Looks good so far. But...
Can I have Two backups?
I would like Daily (no timelapse no uploads)
But on Monday morning I would like Daily (no timelapse)

**Comment by jneilliii** [comment]
I figure this request would come about eventually. I'll take a look at splitting the 3 options so they don't share the same settings.

**Comment by CmdrCody51** [comment]
> I figure this request would come about eventually. I'll take a look at splitting the 3 options so they don't share the same settings.

Closer! But...
I really wanted to be able to change each days backups.

>> I would like Daily (no timelapse no uploads)
>> But on Monday morning I would like Daily (no timelapse)

Rephrasing:
Tuesday thru Sunday at 03:21 AM - backup OctoPrint with NO uploads and NO timelapse
Monday at 03:21 AM - backup OctoPrint WITH uploads and NO timelapse

In 0.0.2 I see you split Daily and Weekly but no options to change backup parameters between them.

**Comment by CmdrCody51** [comment]
Looking good enough for me 8-)
