### ISSUE TITLE
[FR]:  Execute script after backup

### ISSUE THREAD

**Issue by acer8888** [jneilliii/OctoPrint-BackupScheduler#25]
**Is your feature request related to a problem? Please describe.**
No problem, plugin works great as it is!

**Describe the solution you'd like**
After the backup has ran it would be nice to have an option to run a script, in my instance it would upload the backup to my cloud using rclone.

**Describe alternatives you've considered**
Right now I have to space out how long the backup usually takes and use crontab for the script. However he larger the files on the backup the longer the backup takes and could eventually run over.

**Comment by jneilliii** [comment]
You can actually do this with event manager in OctoPrint's settings for the backup complete event. It will pass a payload to your script that includes a path variable to the backup file.

**Comment by acer8888** [comment]
Hey @jneilliii 

Awesome! i was unaware of this. Thank you, tested and it works great!

**Comment by jneilliii** [comment]
Great. interestingly enough, I also contributed the event manager plugin to core OctoPrint. The functionality has always been there but you could only manually edit config.yaml to set it up previously.
