### ISSUE TITLE
[Feature Request]: Upload to network share

### ISSUE THREAD

**Issue by fnsign** [jneilliii/OctoPrint-BackupScheduler#3]
That's a very useful plugin for me! Thanks!

I have a feature request:
I'd like to have the possibility to let the plugin upload the latest backup automatically to a network share which I could specify. That could be done e.g. by mounting the share via smb or transferring the backup file via FTP. 
That way I don't have to bother if there is enough space on the SD and I had a copy of the backup in a second storage.

Thanks again!

**Comment by jneilliii** [comment]
That's outside of the scope of this plugin, but I did make this plugin as a companion to my GoogleDriveBackup plugin, work in octoprint 1.5.1. It would be fairly easy to fork that plugin and make it upload to ftp/nas, etc. instead of Google Drive.

**Comment by jneilliii** [comment]
@fnsign you may find this information helpful.

https://github.com/jneilliii/OctoPrint-BackupScheduler/wiki/Copy-to-NAS

**Comment by fnsign** [comment]
Thanks for that Info! I'll give it a try.
