### ISSUE TITLE
Log flood

### ISSUE THREAD

**Issue by Pavulon87** [jneilliii/OctoPrint-BackupScheduler#6]
I think that on_event is launching too often while printing
> 2020-09-22 09:11:20,822 - octoprint.plugins.backupscheduler - INFO - Scheduling backup for 02:25.
> 2020-09-22 09:11:21,165 - octoprint.plugins.backupscheduler - INFO - Clearing scheduled jobs.
> 2020-09-22 09:11:21,166 - octoprint.plugins.backupscheduler - INFO - Scheduling backup for 02:25.
> 2020-09-22 09:11:21,326 - octoprint.plugins.backupscheduler - INFO - Clearing scheduled jobs.
> 2020-09-22 09:11:21,327 - octoprint.plugins.backupscheduler - INFO - Scheduling backup for 02:25.
> 2020-09-22 09:11:21,499 - octoprint.plugins.backupscheduler - INFO - Clearing scheduled jobs.
> 2020-09-22 09:11:21,501 - octoprint.plugins.backupscheduler - INFO - Scheduling backup for 02:25.
> 2020-09-22 09:11:21,664 - octoprint.plugins.backupscheduler - INFO - Clearing scheduled jobs.
> 2020-09-22 09:11:21,665 - octoprint.plugins.backupscheduler - INFO - Scheduling backup for 02:25.
> 2020-09-22 09:11:21,954 - octoprint.plugins.backupscheduler - INFO - Clearing scheduled jobs.
> 2020-09-22 09:11:21,956 - octoprint.plugins.backupscheduler - INFO - Scheduling backup for 02:25.
> 2020-09-22 09:11:22,158 - octoprint.plugins.backupscheduler - INFO - Clearing scheduled jobs.
> 2020-09-22 09:11:22,159 - octoprint.plugins.backupscheduler - INFO - Scheduling backup for 02:25.
> 2020-09-22 09:11:22,299 - octoprint.plugins.backupscheduler - INFO - Clearing scheduled jobs.
> 2020-09-22 09:11:22,300 - octoprint.plugins.backupscheduler - INFO - Scheduling backup for 02:25.
> 2020-09-22 09:11:22,418 - octoprint.plugins.backupscheduler - INFO - Clearing scheduled jobs.
> 2020-09-22 09:11:22,420 - octoprint.plugins.backupscheduler - INFO - Scheduling backup for 02:25.
> 2020-09-22 09:11:22,881 - octoprint.plugins.backupscheduler - INFO - Clearing scheduled jobs.
> 2020-09-22 09:11:22,883 - octoprint.plugins.backupscheduler - INFO - Scheduling backup for 02:25.
> 2020-09-22 09:11:22,893 - octoprint.plugins.backupscheduler - INFO - Clearing scheduled jobs.
> 2020-09-22 09:11:22,896 - octoprint.plugins.backupscheduler - INFO - Scheduling backup for 02:25.
> 2020-09-22 09:11:22,905 - octoprint.plugins.backupscheduler - INFO - Clearing scheduled jobs.
> 2020-09-22 09:11:22,906 - octoprint.plugins.backupscheduler - INFO - Scheduling backup for 02:25.
> 2020-09-22 09:11:23,609 - octoprint.plugins.backupscheduler - INFO - Clearing scheduled jobs.
> 2020-09-22 09:11:23,610 - octoprint.plugins.backupscheduler - INFO - Scheduling backup for 02:25.
> 2020-09-22 09:11:23,743 - octoprint.plugins.backupscheduler - INFO - Clearing scheduled jobs.
> 2020-09-22 09:11:23,744 - octoprint.plugins.backupscheduler - INFO - Scheduling backup for 02:25.
> 2020-09-22 09:11:25,823 - octoprint.plugins.backupscheduler - INFO - Clearing scheduled jobs.
> 2020-09-22 09:11:25,825 - octoprint.plugins.backupscheduler - INFO - Scheduling backup for 02:25.
> 2020-09-22 09:11:25,878 - octoprint.plugins.backupscheduler - INFO - Clearing scheduled jobs.
> 2020-09-22 09:11:25,880 - octoprint.plugins.backupscheduler - INFO - Scheduling backup for 02:25.
> 2020-09-22 09:11:29,191 - octoprint.plugins.backupscheduler - INFO - Clearing scheduled jobs.
> 2020-09-22 09:11:29,193 - octoprint.plugins.backupscheduler - INFO - Scheduling backup for 02:25.
> 2020-09-22 09:11:29,347 - octoprint.plugins.backupscheduler - INFO - Clearing scheduled jobs.
> 2020-09-22 09:11:29,349 - octoprint.plugins.backupscheduler - INFO - Scheduling backup for 02:25.
> 2020-09-22 09:11:30,207 - octoprint.plugins.backupscheduler - INFO - Clearing scheduled jobs.
> 2020-09-22 09:11:30,209 - octoprint.plugins.backupscheduler - INFO - Scheduling backup for 02:25.
> 2020-09-22 09:11:30,222 - octoprint.plugins.backupscheduler - INFO - Clearing scheduled jobs.
> 2020-09-22 09:11:30,224 - octoprint.plugins.backupscheduler - INFO - Scheduling backup for 02:25.
> 2020-09-22 09:11:30,234 - octoprint.plugins.backupscheduler - INFO - Clearing scheduled jobs.
> 2020-09-22 09:11:30,235 - octoprint.plugins.backupscheduler - INFO - Scheduling backup for 02:25.
> 2020-09-22 09:11:30,242 - octoprint.plugins.backupscheduler - INFO - Clearing scheduled jobs.
> 2020-09-22 09:11:30,244 - octoprint.plugins.backupscheduler - INFO - Scheduling backup for 02:25.
> 2020-09-22 09:11:30,263 - octoprint.plugins.backupscheduler - INFO - Clearing scheduled jobs.
> 2020-09-22 09:11:30,264 - octoprint.plugins.backupscheduler - INFO - Scheduling backup for 02:25.
> 2020-09-22 09:11:46,660 - octoprint.plugins.backupscheduler - INFO - Clearing scheduled jobs.
> 2020-09-22 09:11:46,661 - octoprint.plugins.backupscheduler - INFO - Scheduling backup for 02:25.
> 2020-09-22 09:11:47,996 - octoprint.plugins.backupscheduler - INFO - Clearing scheduled jobs.
> 2020-09-22 09:11:47,997 - octoprint.plugins.backupscheduler - INFO - Scheduling backup for 02:25.
> 2020-09-22 09:11:48,077 - octoprint.plugins.backupscheduler - INFO - Clearing scheduled jobs.
> 2020-09-22 09:11:48,078 - octoprint.plugins.backupscheduler - INFO - Scheduling backup for 02:25.
> 2020-09-22 09:11:48,218 - octoprint.plugins.backupscheduler - INFO - Clearing scheduled jobs.
> 2020-09-22 09:11:48,220 - octoprint.plugins.backupscheduler - INFO - Scheduling backup for 02:25.

**Comment by jneilliii** [comment]
Yeah, I'll switch those to debug so they don't flood the log.

**Comment by jneilliii** [comment]
This is resolved by the above commit, and will be included in the next version release.
