### ISSUE TITLE
[BUG]: time picker not showing

### ISSUE THREAD

**Issue by blalor** [jneilliii/OctoPrint-BackupScheduler#8]
**Describe the bug**

Safari 14.0, macOS 10.14.6. Time of day field is just an empty text field with no suggestion as to supported formats.

**Expected behavior**

The pictured time picker should show, validation should be applied.

**Screenshots**

<img width="671" alt="image" src="https://user-images.githubusercontent.com/109915/94024829-d983e980-fd85-11ea-8e10-14732be439ff.png">

**Comment by jneilliii** [comment]
I can't control how your choice of browser chooses to render a time input field. I'm using a standard  As you can see from this link, safari doesn't support it.

https://www.w3schools.com/tags/att_input_type_time.asp

**Comment by blalor** [comment]
You can gracefully fall back, however, and you can also provide validation that I didn't type `bob` for a time.

**Comment by jneilliii** [comment]
Does it not fallback to a standard input for you? I'll look into adding validation.

**Comment by blalor** [comment]
I see what's in the screenshot.  If I type `bob` in the `Time of Day` field, it saves with no warning.

**Comment by jneilliii** [comment]
> I'll look into adding validation.

That's why I said this...

**Comment by jneilliii** [comment]
I've added the validation to at least give a visual queue of how to enter the time correctly (24 hour format). Could you test it out for me and make sure it's working in safari. Install by copying/pasting the URL below into Plugin Manager > Get More > ...from URL and pressing Install button.

```
https://github.com/jneilliii/OctoPrint-BackupScheduler/archive/0.0.4.zip
```
